### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by taha-shah858** [jerry08/AniStream#21]
When opening a episode, as it is still loading and then gowing back from it ,the app crashes 
  Idk if this is important or not because I don't use 9 anime or zoro but 9 anime is loading infinitely and zoro's subtitles are in Arabic 

Love the app👍

**Comment by jerry08** [comment]
I'll take a look at the first issue you mentioned and fix it asap. For Zoro's subtitles, I recently fixed that bug so that English will be the default subtitles. Those fixes will be included in the next release. Later, I'll add the option to select subtitles. As for the issue with 9anime, I don't know why it's not working anymore. Maybe they changed their keys or algorithm. I'll attempt to fix it and see how it goes.

Thanks
