### ISSUE TITLE
Android TV Issues

### ISSUE THREAD

**Issue by Huzzu-BCMW** [jerry08/AniStream#23]
So I downloaded it on my Android TV through 'Send Files To Tv' and installed it.... First of all it doesn't show in the menu and I have to install a sideload launcher to open it *EASILY*. And second is that whenever I play any Anime, the playback menu can't be accessed through the remote, I can't even pause the anime. I have to connect an external mouse to control it. So I request you look after this.

**Comment by animegamer4422** [comment]
> So I downloaded it on my Android TV through 'Send Files To Tv' and installed it.... First of all it doesn't show in the menu and I have to install a sideload launcher to open it _EASILY_. And second is that whenever I play any Anime, the playback menu can't be accessed through the remote, I can't even pause the anime. I have to connect an external mouse to control it. So I request you look after this.

i understand your frustrations but since this is a app that has yet to mature the primary audience are probably Smartphone users , i'd like to suggest you this project which is more focused on providing a better TV experience instead 
https://github.com/kemuriXD/SaikouTV

Thanks for your time and Have a Great Day

**Comment by jerry08** [comment]
@Huzzu-BCMW Thanks for checking out my little project. Currently, I don't plan on supporting Android TV since it would take too much time and resources (which I don't have). I'm about to redo the entire project using MAUI. It'll support Android, iOS and Windows. Maybe that could be a possible alternative for you. If not, you can follow up the suggestion by @animegamer4422 (thanks for the suggestion. I might port that project into mine later)

**Comment by Huzzu-BCMW** [comment]
Thanks for the information
